### ISSUE TITLE
[Add]  Please display the "(recalled)" text, so we can know which message has been recalled.

### ISSUE THREAD

**Issue by razilong** [Nep-Timeline/Telegram-AntiRecall#2]
![cbfa6987d5ea541add2858b5e57e83b2_4a455642-568b-4ce3-b258-8a3f0f9d31cd](https://github.com/Sakion-Team/Telegram-AntiRecall/assets/97635957/46abea16-8f3d-4f69-aee3-828f491d91f9)

**Comment by Nep-Timeline** [comment]
Do you have a way to do this?

**Comment by rushiranpise** [comment]
> Do you have a way to do this?

Maybe this can help https://github.com/dirname/TMoe/commit/570d4f8c52665e544a541d23dc957cf20a4e88ff

**Comment by Nep-Timeline** [comment]
> > Do you have a way to do this?
> 
> Maybe this can help [dirname/TMoe@570d4f8](https://github.com/dirname/TMoe/commit/570d4f8c52665e544a541d23dc957cf20a4e88ff)

Okay, let me research :)

**Comment by Nep-Timeline** [comment]
try the latest version, this feature is currently incomplete
I use nekogram for support this feature. If there are any bugs on other clients, please tell me :)

**Comment by razilong** [comment]
> try the latest version, this feature is currently incomplete I use nekogram for support this feature. If there are any bugs on other clients, please tell me :)

😘
"(recalled)"  translate吓可唔可以
"(已撤回)"    咁樣順眼嘛

**Comment by Nep-Timeline** [comment]
> > try the latest version, this feature is currently incomplete I use nekogram for support this feature. If there are any bugs on other clients, please tell me :)
> 
> 😘 "(recalled)" translate吓可唔可以 "(已撤回)" 咁樣順眼嘛

ok
