### ISSUE TITLE
[ADD] Nullgram Support?

### ISSUE THREAD

**Issue by rushiranpise** [Nep-Timeline/Telegram-AntiRecall#3]
why is nullgram not supported anymore

**Comment by rushiranpise** [comment]
Also is there any telegram support group?

**Comment by Nep-Timeline** [comment]
Can support to nullgram but nullgram is obfuscated, nnngram is not obfuscate. Nnngram is just a modified version of Nullgram
So unless you have any special requirements, I suggest using Nnngram.
Of course, if you need to use Nullgram, I will also add support back to the Nullgram client
